### PR TITLE
Add guest_info attribute for VMs.

### PR DESCRIPTION
**Pull request by roliveri**
Depends on:
https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/111

### CODE REVIEW

**Review by slemrmartin — APPROVED** [review]
:+1:

**Comment by roliveri** [comment]
This should be ready to merge.

**Review by lindgrenj6 — APPROVED** [review]

**Comment by roliveri** [comment]
@lindgrenj6 Will you release a new version of this GEM?

**Comment by lindgrenj6** [comment]
I don't have access. I'll open up a PR on here to get the auto-releases going, but for now @slemrmartin can you release this quick?

**Pull request merged**
