### PR TITLE
Add host reference to vm

### PR DESCRIPTION
**Pull request by agrare**
https://github.com/ManageIQ/topological_inventory-ingress_api/pull/73

### CODE REVIEW

**Comment by agrare** [comment]
Looks like a lot of stuff added by the generator, @slemrmartin does this look right?

**Comment by slemrmartin** [comment]
@agrare I deleted all of these AllOf classes (including docs/specs and requires) after generating. It's a reported issue in generator's repo.

**Comment by agrare** [comment]
Gotcha, okay removed PTAL

**Comment by agrare** [comment]
@gtanzillo PTAL

**Pull request merged**
